import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from '../app/styles/Home.module.css';
import "bootstrap/dist/css/bootstrap.min.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
      <nav className={`${styles.nav}`}>
            <img className={`ms-5 p-2 ${styles.logoMunicipalidad}`} src="\logoMunicipalidadBlanco.png" alt="logoMunicipalidad" id="logoMunicipalidad"/>
            <h1 className={` ${styles.titulo}`}>Registro de Conducir</h1>
      </nav>
      <div className={styles.lineaAzul}>
             
      </div>
      {children}   
      </body>
    </html>
    
  );
}
